#!/bin/sh

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
PARENT_DIR=$(cd "${SCRIPT_DIR}/../"; pwd)

# install vim-plug automatically
if [ ! -e ${HOME}/.vim/autoload/plug.vim ]; then
  curl -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u ${HOME}/.vimrc +PlugInstall +PlugClean! +qa

# install tmux package manager (tpm) automatically
if [ ! -e ${HOME}/.vim/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm
fi
${HOME}/.tmux/plugins/tpm/bin/install_plugins

files=("${base_dir}/tag-rofi/config")
Xresources="${base_dir}/tag-x/Xresources"

# @see https://github.com/npm/npm/issues/11283
npm config set progress false

# install global npm modules
npm config set prefix ${HOME}/.node_modules
npm install --global \
  babel-cli \
  csscomb \
  eslint \
  eslint_d \
  gulp \
  plop \
  pm2
